### ISSUE TITLE
which version of caffe do you use?

### ISSUE THREAD

**Issue by icbcbicc** [ZhiwenShao/dense-landmark-location#1]
Hello, since I need to run this code on Ubuntu14.04, I'm trying to compile your modified loss code with the latest caffe(16467ff), but many errors occured during building. It seems that your codes use many old version caffe libraries. Can you tell me which vesion of caffe do you use?

 I also tried to compile your [Caffe-bn-windows](https://github.com/ZhiwenShao/Caffe-bn-windows) code on Ubuntu, but failed again. It says the project lacks many .h files. Is there any way I could compile it on Ubuntu?

Thanks

**Comment by ZhiwenShao** [comment]
Hello, the provided code can only be built successfully on windows without modification. You can use the caffe  from https://github.com/mmoghimi, and replace the bn layers with the ones in  Caffe-bn-windows. You should also change the file caffe.proto, and replace corresponding parts with following codes:
// Message that stores parameters used by BNLayer
message BNParameter {
  optional FillerParameter scale_filler = 1; // The filler for the scale
  optional FillerParameter shift_filler = 2; // The filler for the shift
  optional bool use_global_stats = 3;
}
Good Luck
